#!/bin/sh

CLIENT=$1
CLIENT_HOST=$(echo $CLIENT | cut -d ':' -f 1)
CLIENT_PORT=$(echo $CLIENT | cut -d ':' -f 2)

WORKER=$2
WORKER_HOST=$(echo $WORKER | cut -d ':' -f 1)
WORKER_PORT=$(echo $WORKER | cut -d ':' -f 2)

CARGO_HOME=/home/concc/.cargo

ssh -p $WORKER_PORT $WORKER_HOST gosu concc mkdir -p $CARGO_HOME
ssh -p $WORKER_PORT concc@$WORKER_HOST \
  sshfs -p $CLIENT_PORT concc@$CLIENT_HOST:$CARGO_HOME $CARGO_HOME
