#!/bin/sh

EXEC_LOCAL=0
EXEC_REMOTE=1
CMD="$@"

case "$1" in
  /usr/bin/python3)
    case "$2" in
      */gcc_link_wrapper.py)
        exit $EXEC_LOCAL
        ;;
      */gcc_solink_wrapper.py)
        exit $EXEC_LOCAL
        ;;
      */third_party/perfetto/tools/touch_file.py)
        exit $EXEC_LOCAL
        ;;
      *)
        break
        ;;
    esac
    ;;
  *)
    break
    ;;
esac

exit $EXEC_REMOTE
