#!/bin/sh

PYTHON3=$(which python3)
mv $PYTHON3 ${PYTHON3}.local
cat <<EOF >$PYTHON3
#!/bin/sh
if [ "\$CONCC_RUN_LOCALLY" = 1 ]
then
  ${PYTHON3}.local "\$@"
else
  concc-dispatch $PYTHON3 "\$@"
fi
EOF
chmod +x $PYTHON3
