version: '3'

services:
  client:
    image: chromium-buildenv
    init: true
    volumes:
      - .:/workspace

  worker:
    image: chromium-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
