version: '3'

services:
  client:
    image: chromium-buildenv
    init: true
    volumes:
      - ./workspace:/workspace
      - ./scripts:/opt/concc/scripts
    secrets:
      - concc

  worker:
    image: chromium-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse

  project:
    image: atmoz/sftp  # Use corilus/sftp for debugging
    init: true
    ports:
      - '2222:22/tcp'
    volumes:
      - ./workspace:/home/concc/workspace
      - ./secrets.txt:/etc/sftp/users.conf:ro
    secrets:
      - concc

secrets:
  concc:
    file: ./secrets.txt
