version: '3'

services:
  client:
    image: gcc-buildenv
    init: true
    volumes:
      - ./workspace:/workspace
      - ./scripts:/opt/concc/scripts
      - /tmp/strace:/strace
    secrets:
      - password
    # We cannot define CC as an environment variable so that `configure` works
    # properly.

  worker:
    image: gcc-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /tmp/strace:/strace

  project:
    image: atmoz/sftp
    #image: corilus/sftp  # for debugging
    init: true
    ports:
      - '2222:22/tcp'
    volumes:
      - ./workspace:/home/concc/workspace
      - ./users.conf:/etc/sftp/users.conf:ro

secrets:
  password:
    file: ./password
