version: '3'

services:
  client:
    image: gcc-buildenv
    init: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./workspace:/workspace
      - ./scripts:/opt/concc/scripts
      - /tmp/strace:/strace
    tmpfs:
      - /tmp
    secrets:
      - password
    logging:
      driver: none
    # We cannot define CC as an environment variable so that `configure` works
    # properly.

  worker:
    image: gcc-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - /tmp/strace:/strace
    tmpfs:
      - /tmp

  project:
    image: masnagam/concc-sftp
    build:
      dockerfile: ../Dockerfile.sftp
      args:
        BASE: atmoz/sftp
        #BASE: corilus/sftp  # for debugging
    init: true
    cap_add:
      - NET_ADMIN
    ports:
      - '2222:22/tcp'
    volumes:
      - ./workspace:/home/concc/workspace
      - ./users.conf:/etc/sftp/users.conf:ro
    tmpfs:
      - /tmp

secrets:
  password:
    file: ./password
