version: '3'

services:
  client:
    image: rust-buildenv
    init: true
    cap_add:
      - NET_ADMIN
    volumes:
      - ./workspace:/workspace
    tmpfs:
      - /tmp
    secrets:
      - password
    logging:
      driver: none

  worker:
    image: rust-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - NET_ADMIN
    privileged: true
    devices:
      - /dev/fuse:/dev/fuse
    tmpfs:
      - /tmp

  project:
    image: masnagam/concc-sftp
    build:
      dockerfile: ../Dockerfile.sftp
      args:
        BASE: atmoz/sftp
        #BASE: corilus/sftp  # for debugging
    init: true
    cap_add:
      - NET_ADMIN
    ports:
      - '2222:22/tcp'
    volumes:
      - ./workspace:/home/concc/workspace
      - ./users.conf:/etc/sftp/users.conf:ro
    tmpfs:
      - /tmp

secrets:
  password:
    file: ./password
