version: '3'

services:
  client:
    image: rust-buildenv
    init: true
    volumes:
      - ./workspace:/workspace
    environment:
      RUSTC_WRAPPER: /usr/local/bin/concc-dispatch

  worker:
    image: rust-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse
