version: '3'

services:
  client:
    image: rust-buildenv
    init: true
    volumes:
      - ./workspace:/workspace
    secrets:
      - password

  worker:
    image: rust-buildenv
    init: true
    command: >-
      concc-worker
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse

  project:
    image: atmoz/sftp
    #image: corilus/sftp  # for debugging
    init: true
    ports:
      - '2222:22/tcp'
    volumes:
      - ./workspace:/home/concc/workspace
      - ./users.conf:/etc/sftp/users.conf:ro

secrets:
  password:
    file: ./password
