name: CI

on:
  push:
    branches:
      - main
      - trial-*
    paths-ignore:
      - '**.md'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup QEMU user-mode emulation
        uses: docker/setup-qemu-action@v1
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: /tmp/.docker-cache
          key: ${{ runner.os }}-docker-cache-${{ hashFiles('docker/Dockerfile', 'docker/setup.sh', 'docker/tools/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-docker-cache-
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push (mirakc/mirakc)
        uses: docker/build-push-action@v2
        with:
          context: docker
          platforms: linux/amd64
          tags: 'masnagam/concc-tools:latest'
          cache-from: |
            type=local,src=/tmp/.docker-cache
          cache-to: |
            type=local,dest=/tmp/.docker-cache-new
          push: true
      - name: Move cache
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        run: |
          rm -rf /tmp/.docker-cache
          mv /tmp/.docker-cache-new /tmp/.docker-cache
